# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Will Soper
tagline:             A simple blog for notes
url:                 http://willsoper.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Will Soper
  url:               https://twitter.com/WillSoper
  email:             redacted@redacted.com

# Custom vars
version:             1.0.0
github:
  repo:              http://willsoper.github.io/
